part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const LOGIN = _Paths.LOGIN;
  static const OTP_VERIFICATION = _Paths.OTP_VERIFICATION;
  static const PROFILE = _Paths.PROFILE;
  static const PROFILE_DETAILS = _Paths.PROFILE_DETAILS;
  static const PROFILE_EDIT_DETAILS = _Paths.PROFILE_EDIT_DETAILS;
  static const FINANCIAL_DETAILS = _Paths.FINANCIAL_DETAILS;
  static const ADDITIONAL_DETAILS = _Paths.ADDITIONAL_DETAILS;
  static const DASHBOARD = _Paths.DASHBOARD;
  static const HEADER = _Paths.HEADER;
  static const FOOTER = _Paths.FOOTER;
  static const TRANSACTIONS = _Paths.TRANSACTIONS;
  static const DOWNLOAD = _Paths.DOWNLOAD;
  static const HELP = _Paths.HELP;
  static const FILTERS = _Paths.FILTERS;
  static const MOBILE_RECHARGE = _Paths.MOBILE_RECHARGE;
  static const LOAN_REPAYMENT = _Paths.LOAN_REPAYMENT;
  static const QRCODESCANNER = _Paths.QRCODESCANNER;
  static const TO_BANK_UPI_ID = _Paths.TO_BANK_UPI_ID;
  static const TO_SELF_ACCOUNT = _Paths.TO_SELF_ACCOUNT;
  static const SELECT_RECEIVER_BANK_ACCOUNT =
      _Paths.SELECT_RECEIVER_BANK_ACCOUNT;
  static const ADD_UPI_NUMBER = _Paths.ADD_UPI_NUMBER;
  static const ADD_UPI_ID = _Paths.ADD_UPI_ID;
  static const QR_CODE_SCANNER = _Paths.QR_CODE_SCANNER;
  static const SCANNED_PAYMENT_DETAILS = _Paths.SCANNED_PAYMENT_DETAILS;
  static const TO_MOBILE_NO = _Paths.TO_MOBILE_NO;
  static const TO_MOBILE_NUM_PAYMENT_DETAILS =
      _Paths.TO_MOBILE_NUM_PAYMENT_DETAILS;
  // static const QR_CODE_SCANNER = _Paths.QR_CODE_SCANNER;
  static const QUESTIONNAIRE = _Paths.QUESTIONNAIRE;
  static const CREDIT_CARD_REPAYMENT = _Paths.CREDIT_CARD_REPAYMENT;
  static const RENT = _Paths.RENT;
  static const BILLS_RECHARGES = _Paths.BILLS_RECHARGES;
  static const BILLS_AND_RECHARGES = _Paths.BILLS_AND_RECHARGES;
  static const PURCHASES = _Paths.PURCHASES;
  static const TRAVEL = _Paths.TRAVEL;
  static const TRANSIT_AND_FOOD = _Paths.TRANSIT_AND_FOOD;
  static const FASTAG_RECHARGE = _Paths.FASTAG_RECHARGE;
  static const DTH = _Paths.DTH;
  static const PIPED_GAS = _Paths.PIPED_GAS;
  static const LOAN = _Paths.LOAN;
  static const BIKELOAN = _Paths.BIKELOAN;
  static const GOLDLOAN = _Paths.GOLDLOAN;
  static const MUTUALFUNDLOAN = _Paths.MUTUALFUNDLOAN;
  static const CREDITSCORE = _Paths.CREDITSCORE;
  static const TOPPERFORMING = _Paths.TOPPERFORMING;
  static const LARGECAPFUNDS = _Paths.LARGECAPFUNDS;
  static const STARTWITH = _Paths.STARTWITH;
  static const BESTSIPFUNDS = _Paths.BESTSIPFUNDS;
  static const RECEIVEMONEY = _Paths.RECEIVEMONEY;
  static const PHONEPEWALLET = _Paths.PHONEPEWALLET;
  static const PHONEPEGIFTCARD = _Paths.PHONEPEGIFTCARD;
  static const BANKACCOUNTS = _Paths.BANKACCOUNTS;
  static const RUPAYCREDITONUPI = _Paths.RUPAYCREDITONUPI;
  static const CREDITLINEONUPI = _Paths.CREDITLINEONUPI;
  static const UPILITE = _Paths.UPILITE;
  static const AUTOPAY = _Paths.AUTOPAY;
  static const DEBITANDCREDITCARDS = _Paths.DEBITANDCREDITCARDS;
  static const INTERNATIONAL = _Paths.INTERNATIONAL;
  static const UPISETTINGS = _Paths.UPISETTINGS;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const LOGIN = '/login';
  static const OTP_VERIFICATION = '/otp-verification';
  static const PROFILE = '/profile';
  static const PROFILE_DETAILS = '/profile-details';
  static const PROFILE_EDIT_DETAILS = '/profile-edit-details';
  static const FINANCIAL_DETAILS = '/financial-details';
  static const ADDITIONAL_DETAILS = '/additional-details';

  static const DASHBOARD = '/dashboard';
  static const HEADER = '/header';

  static const FOOTER = '/footer';
  static const QRCODESCANNER = '/qrcodescanner';
  static const TO_BANK_UPI_ID = '/to-bank-upi-id';
  static const TO_SELF_ACCOUNT = '/to-self-account';
  static const SELECT_RECEIVER_BANK_ACCOUNT = '/select-receiver-bank-account';
  static const ADD_UPI_NUMBER = '/add-upi-number';
  static const ADD_UPI_ID = '/add-upi-id';
  static const QR_CODE_SCANNER = '/qr-code-scanner';
  static const QUESTIONNAIRE = '/questionnaire';
  static const TO_MOBILE_NO = '/to-mobile_no';

  static const TRANSACTIONS = '/transactions';
  static const DOWNLOAD = '/download';
  static const HELP = '/help';
  static const FILTERS = '/filters';
  static const MOBILE_RECHARGE = '/mobile-recharge';
  static const LOAN_REPAYMENT = '/loan-repayment';
  static const CREDIT_CARD_REPAYMENT = '/credit-card-repayment';
  static const RENT = '/rent';
  static const BILLS_RECHARGES = '/bills-recharges';
  static const BILLS_AND_RECHARGES = '/bills-and-recharges';
  static const PURCHASES = '/purchases';
  static const TRAVEL = '/travel';
  static const TRANSIT_AND_FOOD = '/transit-and-food';
  static const FASTAG_RECHARGE = '/fastag-recharge';
  static const DTH = '/dth';
  static const PIPED_GAS = '/piped-gas';
  static const LOAN = '/loan';
  static const BIKELOAN = '/bikeloan';
  static const GOLDLOAN = '/goldloan';
  static const MUTUALFUNDLOAN = '/mutualfundloan';
  static const CREDITSCORE = '/creditscore';
  static const TOPPERFORMING = '/topperforming';
  static const LARGECAPFUNDS = '/largecapfunds';
  static const STARTWITH = '/startwith';
  static const BESTSIPFUNDS = '/bestsipfunds';
  static const RECEIVEMONEY = '/receivemoney';
  static const PHONEPEWALLET = '/phonepewallet';
  static const PHONEPEGIFTCARD = '/phoneprgiftcard';
  static const SCANNED_PAYMENT_DETAILS = '/scanned_payment_details';
  static const TO_MOBILE_NUM_PAYMENT_DETAILS = '/to_mobile_num_payment_details';
  static const BANKACCOUNTS = '/bankaccounts';
  static const RUPAYCREDITONUPI = '/rupaycreditonupi';
  static const CREDITLINEONUPI = '/creditlineonupi';
  static const UPILITE = '/upilite';
  static const AUTOPAY = '/autopay';
  static const DEBITANDCREDITCARDS = '/debitandcreditcards';
  static const INTERNATIONAL = '/international';
  static const UPISETTINGS = '/upisettings';
}
